image: python:3.10.6
pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: Unit testing
              caches:
                - pip
              script:
                - pip install -r common_requirements.txt
                - pip install -r dev_requirements.txt
                - python -m pytest ./tests
          - step:
              name: Coverage
              caches:
                - pip
              script:
                - pip install -r common_requirements.txt
                - pip install -r dev_requirements.txt
                - pip install pytest-cov
                - python -m pytest --cov ./ ./tests --cov-fail-under=$MIN_COVERAGE_SCORE --cov-config=./.coveragerc --cov-report term-missing:skip-covered
          - step:
              name: PyLinting
              caches:
                - pip
              script:
                - pip install -r common_requirements.txt
                - pip install -r dev_requirements.txt
                - pip install pylint
                - export WORK_DIR=$BITBUCKET_CLONE_DIR
                - python -m pylint --rcfile ${BITBUCKET_CLONE_DIR}/pipelines/.pylintrc --output-format=colorized ${BITBUCKET_CLONE_DIR}
          - step:
              name: Flake8
              caches:
                - pip
              script:
                - pip install -r common_requirements.txt
                - pip install -r dev_requirements.txt
                - pip install flake8
                - python -m flake8 --max-complexity $FLAKE8_MAX_COMPLEXITY --max-line-length $MAX_LINE_LENGTH --ignore E203 --count --statistics --benchmark  ${BITBUCKET_CLONE_DIR}
